name: Deploy Backend to Elastic Beanstalk

on:
  push:
    branches:
      - main      # Despliegue a producción
      - develop   # Despliegue a staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Obtener el código del repositorio
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # 3. Instalar dependencias del backend
      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Cambia la ruta si no está en el directorio raíz

      # 4. Empaquetar la aplicación en un archivo ZIP
      - name: Package application
        run: |
          zip -r backend.zip .  # Ajusta la ruta según tu estructura de proyecto

      # 5. Debug de los secretos para verificar si están configurados correctamente
      - name: Debug secrets
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}"

      # 6. Desplegar a Elastic Beanstalk
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          application_name: AUSTRALIANPROJECT-BACKEND
          environment_name: ${{ github.ref_name == 'main' ? 'backend-production' : 'backend-staging' }}
          region: us-east-2  # Cambia a tu región si es diferente
          version_label: ${{ github.sha }}
          deployment_package: backend.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
