name: Deploy Backend to Elastic Beanstalk

on:
  push:
    branches:
      - main      # Despliegue a producci칩n
      - develop   # Despliegue a staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Obtener el c칩digo del repositorio
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # 3. Instalar dependencias del backend
      - name: Install dependencies
        run: |
          pip install -r backend/requirements.txt

      # 4. Empaquetar la aplicaci칩n en un archivo ZIP
      - name: Package application
        run: |
          cd backend
          zip -r ../backend.zip .

      # 4.5. Debug de los secretos para verificar si est치n configurados correctamente
      - name: Debug secrets
        run: |
          echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID"
          echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY"

      # 5. Desplegar a Elastic Beanstalk
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          application_name: AUSTRALIANPROJECT-BACKEND
          environment_name: ${{ github.ref_name == 'main' ? 'backend-production' : 'backend-staging' }}
          region: us-east-2
          version_label: ${{ github.sha }}
          deployment_package: backend.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}